on:
  pull_request:
    branches:
      - master
    types: [opened, edited]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Show branches
        run: |
          echo "HEAD: " ${{ github.head_ref }}
          echo "BASE: " ${{ github.base_ref }}

      - name: Install lib dependencies
        run: yarn install

      - name: Set Git credentials
        run: |
          git config user.email "aryella.lacerda@gmail.com"
          git config user.name "Aryella"

      - name: Prepend node path
        run: npm config set scripts-prepend-node-path auto

      - name: Generate version number, commit, tag, and Github release
        run: yarn release --ci