on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}

    steps:
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install lib dependencies
        run: yarn install

      - name: Set Git credentials
        run: |
          git config user.email "aryella.lacerda@gmail.com"
          git config user.name "Aryella"

      - name: Prepend node path
        run: npm config set scripts-prepend-node-path auto

      - name: Generate version number, commit, tag, and Github release
        run: yarn release --ci